### ISSUE TITLE
Make site sections iframes, potentially callable via some CSS so we can use # as extensions to the URL

### ISSUE THREAD

**Issue by Icekhaos** [NicholasG04/scattervolt#6]
This cuts out the need to have elements in *every* site HTML, and actually allows us to edit *one* file and change every page.

**Comment by NicholasG04** [comment]
https://stackoverflow.com/questions/31954089/html-css-navigation-bar-on-multiple-pages

So for a start, we can at least inject nav.html from /frames into pages.... but that gets me thinking. Using the same method of having a div and 'loading' a frame into it we could probably do the exact same thing with onclick and basically remove every other page. Just got to think about logistics here.

**Comment by NicholasG04** [comment]
But I'm really gonna have to think about how index is loaded compared to the rest of the pages. I can pretty much make all of the pages the same 'style' in terms of loading in a background etc but index is totally different. Gotta think about how this is going to work. Need a mostly blank canvas with the header - I'm thinking that by having a 'behind' background (with nav over it) we can then fit it to whatever style suitable. eg in pages with whole page bg we can simply have it transparent, but in others we can layer over colours at certain points etc etc.

**Comment by NicholasG04** [comment]
@Icekhaos I need help thinking this out .-.

**Comment by NicholasG04** [comment]
if pageTitle = xx {
$("#contactLink").attr(.active);
});

**Comment by NicholasG04** [comment]
These issues are very old, but I'm going to start looking at some more website improvements. This is not the future to go down for the website if we're looking at such modularity. I'd prefer to move it to some sort of framework like Flask/Jninja2, React etc than do this.
